packages:
  - "packages/*"
  - "apps/*"

catalog:
  "@types/node": ^22.10.7
  "@tailwindcss/vite": ^4.0.7
  typescript: ~5.7.3
  tailwindcss: ^4.0.1
  clsx: ^2.1.1
  reka-ui: ^2.0.0
  tailwind-merge: ^3.0.2
  tailwind-variants: ^0.3.1